#pragma once
#include "Screen.h"
#include "Game.h"
#include "Ship.h"
#include "Board.h"
#include "Object.h"
#include "Menu.h"
#include "Level.h"
#include "AI.h"
#include <SFML\Graphics.hpp>
#include <SFML\Window.hpp>